

spring:
  application.name: 'finance-backend'
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/finance}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:pwd}
    driver-class-name: 'org.postgresql.Driver'
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa.generate-ddl: ${DATASOURCE_GENERATE_DDL:true}

kafka:
  bootstrap-server: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
  transaction-topic:
    name: ${TRANSACTION_TOPIC_NAME:transaction-json}
    partitions: ${TRANSACTION_TOPIC_PARTITIONS:1}
    replication-factor: ${TRANSACTION_TOPIC_REPLICATION_FACTOR:1}
  producer:
    enable-idempotence: 'true'
    acks: 'all'
    retries: 3

management:
  endpoints:
    web:
      exposure:
        include: health