replicaCount: 2

image:
  repository: "molgergo01/finance-api"
  pullPolicy: Always
  tag: "0.0.1-SNAPSHOT"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

resources: {}

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

datasource:
  url: "jdbc:postgresql://finance-api-bitnami-postgres:5432/finance"
  username: "postgres"
  secretName: "finance-api-bitnami-postgres"
  generateDdl: "true"

kafka:
  bootstrapServer: "finance-api-bitnami-kafka:9092"
  transactionTopic:
    name: "transaction-json"
    partitions: "1"
    replicationFactor: "1"

bitnami-postgres:
  auth:
    database: "finance"
    postgresPassword: 'pwd'

bitnami-kafka:
    listeners:
      client:
        protocol: 'PLAINTEXT'
      controller:
        protocol: 'PLAINTEXT'

